### PR TITLE
Implement Hungarian word order for pages

### PR DESCRIPTION
**Pull request by moewew**
This implements the Hungarian word order "# p." for page/column/verse numbers instead of the English order 'p. #'.

### CODE REVIEW

**Comment by marczellm** [comment]
The dot is missing (at the marked places)

image

**Comment by moewew** [comment]
Does that dot, technically speaking, signify an ordinal number or something else?

**Comment by marczellm** [comment]
Ordinal number. „1. oldal” is equivalent to „First page”, „1-100. oldal” is „First to 100th page” etc.

**Comment by moewew** [comment]
OK, but it is "1-100." with a dot only after the "100", not after "1"?

**Comment by marczellm** [comment]
Yes, it’s `1-100.`

**Comment by moewew** [comment]
Hypothetically, what would need to happen if I had several page ranges in one like "1-20, 30-40, 50"? do all "20", "40" and "50" get the dot or only "50"?

**Comment by marczellm** [comment]
Each range gets a dot.

**Comment by moewew** [comment]
Ah, that is more complicated. I added a first attempt.

**Comment by marczellm** [comment]
I still get no dot in the output.

MWE:
```
\documentclass{article}
\usepackage[magyar]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[backend=biber]{biblatex}
\addbibresource{mwe.bib}
\begin{document}

\cite{c1}

\cite{c2}

\printbibliography

\end{document}
```

mwe.bib:

```
@inproceedings{c1,
  title={Deep Sparse Rectifier Neural Networks},
  author={Glorot, Xavier and Bordes, Antoine and Bengio, Yoshua},
  booktitle={Aistats},
  volume={15},
  number={106},
  pages={275},
  year={2011}
}

@inproceedings{c2,
  title={Introducing the Jazzomat project},
  subtitle={Jazz solo analysis using music information retrieval methods},
  author={Frieler, Klaus and Abe{\ss}er, Jakob and Zaddach, Wolf-Georg and Pfleiderer, Martin},
  booktitle={Proceedings of the 10th International Symposium on Computer Music Multidisciplinary Research},
  pages={187--192},
  year={2013},
  url={http://jazzomat.hfm-weimar.de},
  urldate={2017-04-24}
}
```

**Comment by moewew** [comment]
Try again, please. I had missed a few cases.

**Comment by marczellm** [comment]
Looks good now.

**Pull request merged**
