### PR TITLE
Change volume field order

### PR DESCRIPTION
**Pull request by moewew**
This is an example how to change the order for the volume field. Other fields can be changed similarly. Since you change the format for certain fields you implicitly bas this on a certain style, so this can not be guaranteed to work with all custom styles. Check back with `biblatex.def` to make sure the definitions work.

### CODE REVIEW

**Comment by marczellm** [comment]
To fix the remaining cases where the page numbers don't get the dot, do you recommend this approach (`\DeclareFieldFormat` etc.) _instead of_ or _supplementing_ the low-level redefinitions in marczellm#2?

**Comment by moewew** [comment]
That depends. I'm a bit torn at the moment.

The code from https://github.com/marczellm/biblatex/pull/2 does not give a dot in all situations, but it is compatible with (some) custom styles changing the format of the `pages` field.

If we were to implement a solution similar to what we did here, the format defined in `magyar.lbx` would always overwrite the definitions of custom styles. So suppose we were to implement something in `magyar.lbx` that changes the field formats so that the output is "#. old.", then this would overrule styles that do `\DeclareFieldFormat{pages}{#1}` to obtain only the numbers and no "pp.". This would leave Hungarian bibliographies with pages fields that use a format not intended by the style author.

**Comment by ferdinandyb** [comment]
I agree with @marczellm, that the main goal should be acceptable localisation if a perfect one is not possible. In this case we should probably pick the most common styles and solve those and try to communicate clearly (in the source code also :)) what the solutions breaks.

**Comment by moewew** [comment]
OK. I have reworked the page stuff in https://github.com/marczellm/biblatex/pull/4 to come closer to what I proposed here for volume. What other fields needs reordering?

Please check that the volume changes gives acceptable output for `knuth:ct:a` of `biblatex-examples.bib`.

> Donald E. Knuth. Computers & Typesetting. A köt.: The TeXbook. Reading, Mass.: Addison-Wesley

**Comment by marczellm** [comment]
The format you write is correct, but I cannot reproduce it with the code. I get this with authoryear or no style at all:

image

**Comment by moewew** [comment]
I suppose that is because the change is implemented in this Pull request and it has not been merged yet.

**Comment by marczellm** [comment]
Sorry, I got mixed up between the different branches.

**Comment by marczellm** [comment]
The volume and the number both need to be formatted as an ordinal, with dot. But in this Knuth example where the volume is not a number, the dot is not needed.

The same goes for document sectioning: "Chapter 1" becomes "1. fejezet" etc.

**Comment by moewew** [comment]
This is now over at https://github.com/marczellm/biblatex/pull/5

**Pull request closed without merging**
